### ISSUE TITLE
Add more diagrams/images to Notebook 2

### ISSUE THREAD

**Issue by Bratah123** [KOOKIIEStudios/Computation-in-Python#1]
I think this course could benefit from more images :) specifically one in the Functions section!

---
### references

![image](https://github.com/KOOKIIEStudios/Computation-in-Python/assets/25145447/3897a8be-bf60-4424-af8f-78919a329df3)
![image](https://github.com/KOOKIIEStudios/Computation-in-Python/assets/25145447/e25932a6-117f-40b5-a2fa-692ca358a8cc)

**Comment by KOOKIIEStudios** [comment]
Completed as of: 1533c89435d818dad4468036bb7d9df3faf70d29
